export const MONITOR_INFO_REQUEST = 'MONITOR_INFO_REQUEST';
export const MONITOR_INFO_SUCCESS = 'MONITOR_INFO_SUCCESS';
export const MONITOR_INFO_FAILURE = 'MONITOR_INFO_FAILURE';

export const MONITOR_CONTROL_REQUEST = 'MONITOR_CONTROL_REQUEST';
export const MONITOR_CONTROL_SUCCESS = 'MONITOR_CONTROL_SUCCESS';
export const MONITOR_CONTROL_FAILURE = 'MONITOR_CONTROL_FAILURE';

export const RECEIVE_CONTROL_MESSAGE = 'RECEIVE_CONTROL_MESSAGE';
export const RECEIVE_STATS = 'RECEIVE_STATS';

export const INITIALIZE_MONITOR_REQUEST = 'INITIALIZE_MONITOR_REQUEST';
export const INITIALIZE_MONITOR_SUCCESS = 'INITIALIZE_MONITOR_SUCCESS';
export const INITIALIZE_MONITOR_FAILURE = 'INITIALIZE_MONITOR_FAILURE';
