export const MONITOR_INFO_REQUEST = 'MONITOR_INFO_REQUEST';
export const MONITOR_INFO_SUCCESS = 'MONITOR_INFO_SUCCESS';
export const MONITOR_INFO_FAILURE = 'MONITOR_INFO_FAILURE';

export const MONITOR_CONTROL_REQUEST = 'MONITOR_CONTROL_REQUEST';
export const MONITOR_CONTROL_SUCCESS = 'MONITOR_CONTROL_SUCCESS';
export const MONITOR_CONTROL_FAILURE = 'MONITOR_CONTROL_FAILURE';
