export const INITIALIZE_STOMP = 'INITIALIZE_STOMP';
export const INITIALIZE_STOMP_SUCCESS = 'INITIALIZE_STOMP_SUCCESS';

export const FINALIZE_STOMP = 'FINALIZE_STOMP';
export const FINALIZE_STOMP_SUCCESS = 'FINALIZE_STOMP_SUCCESS';

export const STOMP_ERROR = 'STOMP_ERROR';
